require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Rails:
  Enabled: true

RSpec:
  Enabled: true

RSpecRails:
  Enabled: true

Style/Documentation:
  Enabled: false

Rails/FindEach:
  Enabled: false

AllCops:
  SuggestExtensions: false
